// <auto-generated />
namespace Project.Migrations.Tasks
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TaskTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TaskTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201804022341250_TaskTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
